name: Build and Zip Angular App

on:
  push:
    branches: [ master ]
permissions:
  checks: write
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npx ng build --configuration production

    - name: Zip Artifacts
      run: |
        sudo apt-get install zip
        zip -r dist.zip dist/

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist.zip
